# Generated by Django 4.2.21 on 2025-05-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
    ]
