# Generated by Django 5.0.1 on 2025-05-23 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_pricingsettings_ride_admin_profit_ride_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Évaluation', 'verbose_name_plural': 'Évaluations'},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='criteria',
            field=models.CharField(choices=[('general', 'Général'), ('punctuality', 'Ponctualité'), ('comfort', 'Confort'), ('cleanliness', 'Propreté'), ('communication', 'Communication'), ('driving', 'Conduite')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text="L'évaluation restera anonyme"),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('from_user', 'to_user', 'ride', 'criteria')},
        ),
        migrations.CreateModel(
            name='RideReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inappropriate_behavior', 'Comportement inapproprié'), ('safety_concern', 'Problème de sécurité'), ('no_show', 'Absence au rendez-vous'), ('wrong_vehicle', 'Véhicule différent'), ('dangerous_driving', 'Conduite dangereuse'), ('other', 'Autre')], max_length=30)),
                ('description', models.TextField(help_text='Décrivez en détail le problème rencontré')),
                ('evidence', models.FileField(blank=True, help_text='Photos, vidéos ou autres preuves', upload_to='report_evidence/')),
                ('status', models.CharField(choices=[('pending', 'En attente de traitement'), ('investigating', "En cours d'investigation"), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text="Notes internes pour l'administration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Le signalement restera anonyme')),
                ('requires_immediate_action', models.BooleanField(default=False, help_text='Nécessite une action immédiate')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
    ]
