# Generated by Django 5.0.1 on 2025-05-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_create_groups'),
        ('rides', '0007_alter_rating_options_alter_rating_unique_together_and_more'),
    ]

    operations = [
    ]
